#!/usr/bin/env bash
set -euo pipefail

MISSION_CONTROL_HOST="${MISSION_CONTROL_HOST:-0.0.0.0}"
MISSION_CONTROL_PORT="${MISSION_CONTROL_PORT:-3021}"
OPENCLAW_STATE_DIR="${OPENCLAW_STATE_DIR:-/home/node/.openclaw}"
OPENCLAW_CONFIG_PATH="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_STATE_DIR}/openclaw.json}"
OPENCLAW_MISSION_CONTROL_CONFIG_PATH="${OPENCLAW_MISSION_CONTROL_CONFIG_PATH:-${OPENCLAW_CONFIG_PATH}}"
CLAWDBOT_STATE_DIR="${CLAWDBOT_STATE_DIR:-${OPENCLAW_STATE_DIR}}"
MOLTBOT_STATE_DIR="${MOLTBOT_STATE_DIR:-${OPENCLAW_STATE_DIR}}"

export MISSION_CONTROL_HOST
export MISSION_CONTROL_PORT
export OPENCLAW_STATE_DIR
export OPENCLAW_CONFIG_PATH
export OPENCLAW_MISSION_CONTROL_CONFIG_PATH
export CLAWDBOT_STATE_DIR
export MOLTBOT_STATE_DIR

if [[ -z "${OPENCLAW_MISSION_CONTROL_GATEWAY_URL:-}" ]]; then
  echo "[deploy] OPENCLAW_MISSION_CONTROL_GATEWAY_URL is required." >&2
  exit 1
fi

echo "[deploy] Mission Control config path: $OPENCLAW_MISSION_CONTROL_CONFIG_PATH"
echo "[deploy] Mission Control gateway url: $OPENCLAW_MISSION_CONTROL_GATEWAY_URL"
echo "[deploy] Mission Control bind=${MISSION_CONTROL_HOST} port=${MISSION_CONTROL_PORT}"

exec pnpm --dir /app/apps/mission-control exec next start \
  --hostname "$MISSION_CONTROL_HOST" \
  --port "$MISSION_CONTROL_PORT"
